plugins {
    id 'java'
}

group = 'com.pai.paimc'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: "server/libraries", include: ["**/*.jar"])
    implementation "org.jetbrains:annotations:26.0.2"
    implementation "com.google.code.findbugs:jsr305:3.0.2"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
